keys:
  - &user_shayne age1leyl3znxwnsg6uz6p5zm0vp76p26vy4rfhtgdquphx4c98cky9vq8ydl6x
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_shayne
