host: rk1
appdata:
  - /var/lib/bitwarden_rs
  - /var/lib/tailscale
mounts:
  - /home/shayne/backups/vaultwarden:/backup
devices:
  - /dev/net/tun:/dev/net/tun
privileged: true
cap_add:
  - net_admin
  - sys_module
  - sys_admin