host: pve0
appdata:
  - /var/lib/sabnzbd
  - /var/lib/tailscale
mounts:
  - /mnt/pve/nvme/downloads-complete:/downloads-complete
  - /mnt/pve/nvme/downloads-incomplete:/downloads-incomplete
devices:
  - /dev/net/tun:/dev/net/tun
cap_add:
  - net_admin
  - sys_module