host: pve0
appdata:
  - /var/lib/samba
  - /var/lib/tailscale
mounts:
  - /mnt/rust/media:/media
  - /flash/documents:/documents
  - /flash/backups:/backups
devices:
  - /dev/net/tun:/dev/net/tun
cap_add:
  - net_admin
  - sys_module