host: pve0
appdata:
  - /config
  - /var/lib/tailscale
mounts:
  - /flash/downloads-complete:/downloads-complete
  - /mnt/pve/local-ext4/downloads-incomplete:/downloads-incomplete
  - /mnt/rust/media/tv:/tv
devices:
  - /dev/net/tun:/dev/net/tun
cap_add:
  - net_admin
  - sys_module